apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: tenant
  version: 2.0.0
  repo: https://gnunn-gitops.github.io/helm-charts
  namespace: argocd
  releaseName: rollouts-demo
  valuesFile: values.yaml
  additionalValuesFiles:
    - cluster.values.yaml

resources:
- ../../base
